#ifndef CONFIG_H_ 
#define CONFIG_H_

#include "Vec2.h"

// APP
#define SCREEN_W 1280
#define SCREEN_H 720
#define SET_RND_SEED true
#define RND_SEED 0
#define RUN_CUSTOM_CREATURE false
#define PAUSE_AFTER_FINISH false

// EVOLUTIONARY ALGORITHM
#define N_CREATURES 50
#define N_GENERATIONS 100
#define RUN_TIME_SECS 10
#define RUN_FPS 60
#define RUN_DT 1.f / float(RUN_FPS)
#define BIG_MUT_P 0.15f

// SIMULATION
#define MAX_VELOCITY 1000.f
#define WATER_DRAG_COEF 1.17f
#define WATER_DRAG_COEF_DT 1.00262015577f //powf(WATER_DRAG_COEF, RUN_DT)

// CREATURE
#define MAX_SETTLE_ITERATIONS 1000
#define SETTLE_EPSILON 0.0001f
#define SETTLE_FRICTION_COEF 0.8f
#define CREATURE_MIN_NODES 5
#define CREATURE_MAX_NODES 5
#define EDGE_CONNECT_P 0.5f
#define NODE_RADIUS 12.f

// MUSCLE
#define MAX_MUSCLE_LENGTH 80.f
#define MIN_MUSCLE_LENGTH 50.f
#define CLOCK_SPEED 0.5f
#define STIFFNESS_COEF 100.f
#define DAMPING_COEF 10.f

#endif  // CONFIG_H_